#!/usr/bin/env python

"""
    Author: Mingi Jeong

    node csv_converter
    
    purpose: 
    - main converter node
"""

# python modules
import csv
# from ruamel import yaml

# ROS modules
import rospy

# custom modules
from multibags_to_csv.ConverterMulti import ConverterMulti


def main():
    # node initialization
    rospy.init_node('csv_converter')
    rospy.sleep(1)

    # class instantiation for time sync subscriber
    converter = ConverterMulti()
    # converter.initializer()
    rospy.sleep(1)

    rospy.loginfo("converter initialized")

    # rospy.sleep(1)
    ### main time sync and csv writer
    converter.time_sync_callback()

    while not rospy.is_shutdown():
        rospy.spin() # spin here. Inside sync callback error


if __name__ == '__main__':
    try:
        main()
    except rospy.ROSInterruptException:
        rospy.logerr("executing csv converter node failed")
        pass